services:
  service:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - stack.env
    restart: on-failure
    networks:
      - n8n
      - ccrm-data-collection
    volumes:
      - NAS:/app/nas_data

volumes:
  NAS:
    external: true

networks:
  n8n:
    external: true
  ccrm-data-collection:
    driver: bridge
